### ISSUE TITLE
help.php entfernen, README.md anzeigen?

### ISSUE THREAD

**Issue by schuer** [WolfgangBusch/url_simple_rewrite#1]
Wenn du die `help.php` entfernst, wird beim Klick auf das Fragezeichen im REDAXO-Adminbereich stattdessen die `README.md` ausgegeben. Die enthält in deinem AddOn mehr Infos, vielleicht solltest du das deshalb so machen. Dann musst du danach die Hilfe auch nur noch ein einer Stelle pflegen, nicht mehr an zwei Stellen.

**Comment by WolfgangBusch** [comment]
Da bleibe ich doch bei meiner Version. Die README ist mir dafür ein bisschen zu lang geraten.

In denselben Zusammenhang fällt übrigens auch der einführende Text, den man beim Einrichten eines AddOns in MyREDAXO angibt. Warum kann da nicht automatisch die README.md oder die help.php benutzt werden?

**Comment by schuer** [comment]
Hey Wolfgang, ich würde gerne hier schließen, weil dieses GitHub-Issue in meiner Liste der von mir angelegten Issues auftaucht und ich dann immer das Gefühl habe, es sei noch eine Aufgabe für mich zu erledigen.

Ich hoffe, das ist in Ordnung für dich. Falls nicht, öffne gerne wieder.

**Comment by WolfgangBusch** [comment]
Hallo Dirk, kannst du gerne schließen.Gruß, Wolfgang BuschAm 25.06.23, 11:28 schrieb "Dirk Schürjohann" ***@***.***>:

   
  Hey Wolfgang, ich würde gerne hier schließen, weil dieses GitHub-Issue in meiner Liste der von mir angelegten Issues auftaucht und ich dann immer das Gefühl habe, es sei noch eine Aufgabe für mich zu erledigen. 
  Ich hoffe, das ist in Ordnung für dich. Falls nicht, öffne gerne wieder.
