### ISSUE TITLE
Lizenz?

### ISSUE THREAD

**Issue by schuer** [WolfgangBusch/url_simple_rewrite#2]
Willst du vielleicht noch eine Lizenz anbringen? Das erleichtert/ermöglicht die Nutzung für andere. MIT bietet sich an.

GitHub macht das übrigens sehr geschickt: Wenn du auf der Weboberfläche _Create new file_ benutzt und ins Feld `LICENCE` tippst, schlägt dir GitHub diverse Optionen vor.

**Comment by WolfgangBusch** [comment]
Ich habe gerade eine Kopie der MIT-Lizenz eingefügt. Was anderes/besseres fiel mir nicht ein.

**Comment by schuer** [comment]
👍
