### ISSUE TITLE
install.php und uninstall.php entfernen?

### ISSUE THREAD

**Issue by schuer** [WolfgangBusch/url_simple_rewrite#3]
Die beiden Dateien werden aktuell in deinem AddOn nicht benötigt, deshalb solltest du sie zur besseren Übersicht vielleicht weglassen.

**Comment by WolfgangBusch** [comment]
Mache ich umgehend.

**Comment by schuer** [comment]
Hey Wolfgang, ich würde gerne hier schließen, weil dieses GitHub-Issue in meiner Liste der von mir angelegten Issues auftaucht und ich dann immer das Gefühl habe, es sei noch eine Aufgabe für mich zu erledigen.

Ich hoffe, das ist in Ordnung für dich. Falls nicht, öffne gerne wieder.

**Comment by WolfgangBusch** [comment]
OkGruß, Wolfgang BuschAm 25.06.23, 11:29 schrieb "Dirk Schürjohann" ***@***.***>:

   
  Hey Wolfgang, ich würde gerne hier schließen, weil dieses GitHub-Issue in meiner Liste der von mir angelegten Issues auftaucht und ich dann immer das Gefühl habe, es sei noch eine Aufgabe für mich zu erledigen. 
  Ich hoffe, das ist in Ordnung für dich. Falls nicht, öffne gerne wieder.
