### ISSUE TITLE
Mehrsprachigkeit: EN hinzufügen

### ISSUE THREAD

**Issue by schuer** [WolfgangBusch/url_simple_rewrite#4]
REDAXO öffnet sich langsam für nicht-deutschsprachige Nutzer. Vielleicht hast du Lust, auch Englisch als Sprache hinzuzufügen. Sind nur 3 Strings aktuell, das wäre ja ruckzuck gemacht und würde ein gutes Zeichen setzen! :)

**Comment by WolfgangBusch** [comment]
Hallo Dirk, vielen Dank für deine inzwischen 4 Kommentare und Hinweise. Kann ich alle 4 gut akzeptieren. 
Einen EN-Zweig einzufügen ist tatsächlich ganz einfach. Sinnvoll wäre dann aber auch der nächste Schritt, die gesamten Beschreibungen im Ordner pages auch in englisch zu übersetzen. Lohnt sich das in diesem Falle?

**Comment by schuer** [comment]
Hey Wolfgang, ich denke es wäre sinnvoll, erfordert aber natürlich etwas Aufwand. Wenn du Zeit und Lust hast, würde ich den Schritt gehen. Und wenn nicht, bist du ja mit deinen AddOns nun bei GitHub, so dass andere Nutzer etwas beisteuern können. Vielleicht ergibt sich dadurch was.

**Comment by WolfgangBusch** [comment]
Hallo Dirk,

noch einmal vielen Dank für deine Kommentare zu url_simple_rewrite. Ich 
hatte wohl noch etwas Nachholbedarf im Umgang mit GitHub.
Viel gespannter bin ich auf deine oder andere Kommentare zu meinem 
eigentlichen URL-Rewriter url_path_rewrite. Liegt unter
https://github.com/WolfgangBusch/url_path_rewrite
Da könnte sich das Übersetzen der Beschreibungen vielleicht eher lohnen...

Gruß, Wolfgang,
   Dr. Wolfgang Busch (http://busch-dettum.de/)
-----Ursprüngliche Nachricht-----

**Comment by WolfgangBusch** [comment]
Hallo Dirk, noch einmal vielen Dank für deine Kommentare zu url_simple_rewrite. Ich hatte wohl noch etwas Nachholbedarf im Umgang mit GitHub.
Viel gespannter bin ich auf deine oder andere Kommentare zu meinem eigentlichen URL-Rewriter url_path_rewrite. Liegt unter https://github.com/WolfgangBusch/url_path_rewrite
Da könnte sich das Übersetzen der Beschreibungen vielleicht eher lohnen...

**Comment by WolfgangBusch** [comment]
Mist, wenn man auf die falschen Knöpfe drückt

**Comment by schuer** [comment]
Hey Wolfgang, ich würde gerne hier schließen, weil dieses GitHub-Issue in meiner Liste der von mir angelegten Issues auftaucht und ich dann immer das Gefühl habe, es sei noch eine Aufgabe für mich zu erledigen.

Ich hoffe, das ist in Ordnung für dich. Falls nicht, öffne gerne wieder.

**Comment by WolfgangBusch** [comment]
OkGruß, Wolfgang BuschAm 25.06.23, 11:29 schrieb "Dirk Schürjohann" ***@***.***>:

   
  Hey Wolfgang, ich würde gerne hier schließen, weil dieses GitHub-Issue in meiner Liste der von mir angelegten Issues auftaucht und ich dann immer das Gefühl habe, es sei noch eine Aufgabe für mich zu erledigen. 
  Ich hoffe, das ist in Ordnung für dich. Falls nicht, öffne gerne wieder.
